import { Bookmark, Category, PasswordEntry } from "@/types";

export const INITIAL_CATEGORIES: Category[] = [
  { id: "cat-work", name: "Work", color: "#3b82f6", isDefault: true },
  { id: "cat-dev", name: "Development", color: "#10b981", isDefault: true },
  { id: "cat-finance", name: "Finance", color: "#f59e0b", isDefault: true },
  { id: "cat-social", name: "Social", color: "#ec4899", isDefault: true },
  { id: "cat-shopping", name: "Shopping", color: "#8b5cf6", isDefault: true },
  { id: "cat-personal", name: "Personal", color: "#06b6d4", isDefault: true },
];

export const INITIAL_BOOKMARKS: Bookmark[] = [
  {
    id: "bm-1",
    title: "GitHub",
    url: "https://github.com",
    category: "Development",
    description: "Code hosting and collaboration platform for software projects.",
    isFavorite: true,
    createdAt: Date.now() - 1000000,
    updatedAt: Date.now() - 1000000,
  },
  {
    id: "bm-2",
    title: "Gmail",
    url: "https://mail.google.com",
    category: "Work",
    description: "Personal and professional email communications.",
    isFavorite: true,
    createdAt: Date.now() - 900000,
    updatedAt: Date.now() - 900000,
  },
  {
    id: "bm-3",
    title: "Notion",
    url: "https://notion.so",
    category: "Work",
    description: "Connected workspace for wiki, docs, and project management.",
    isFavorite: true,
    createdAt: Date.now() - 800000,
    updatedAt: Date.now() - 800000,
  },
  {
    id: "bm-4",
    title: "Vercel",
    url: "https://vercel.com",
    category: "Development",
    description: "Frontend cloud deployment platform.",
    isFavorite: false,
    createdAt: Date.now() - 700000,
    updatedAt: Date.now() - 700000,
  },
  {
    id: "bm-5",
    title: "ProtonMail",
    url: "https://proton.me",
    category: "Personal",
    description: "Encrypted email and privacy services.",
    isFavorite: true,
    createdAt: Date.now() - 600000,
    updatedAt: Date.now() - 600000,
  },
];

export const INITIAL_DEMO_VAULT_ITEMS: PasswordEntry[] = [
  {
    id: "pwd-1",
    websiteName: "GitHub",
    websiteUrl: "https://github.com/login",
    username: "alex.developer@example.com",
    password: "xK9#mQ$2vP!8zL5n",
    notes: "Primary account repositories and 2FA enabled.",
    category: "Development",
    totpSecret: "JBSWY3DPEHPK3PXP",
    isFavorite: true,
    createdAt: Date.now() - 1000000,
    updatedAt: Date.now() - 1000000,
  },
  {
    id: "pwd-2",
    websiteName: "Google Account",
    websiteUrl: "https://accounts.google.com",
    username: "alex.developer@example.com",
    password: "gH$7wN*1kX#9yT3m",
    notes: "Primary workspace email and Google Cloud console.",
    category: "Work",
    totpSecret: "HXDMVJECJJWSRB3HWIZR4IFUGFTMXBOZ",
    isFavorite: true,
    createdAt: Date.now() - 900000,
    updatedAt: Date.now() - 900000,
  },
  {
    id: "pwd-3",
    websiteName: "Notion",
    websiteUrl: "https://www.notion.so/login",
    username: "alex.developer@example.com",
    password: "nT!4vR%8pB@2wM6q",
    notes: "Engineering roadmap and internal documentation.",
    category: "Work",
    isFavorite: false,
    createdAt: Date.now() - 800000,
    updatedAt: Date.now() - 800000,
  },
  {
    id: "pwd-4",
    websiteName: "Vercel",
    websiteUrl: "https://vercel.com/login",
    username: "alex.developer@example.com",
    password: "vC&9xK!3mL#7pQ2z",
    notes: "Production deployments, environment secrets, and domain management.",
    category: "Development",
    isFavorite: false,
    createdAt: Date.now() - 700000,
    updatedAt: Date.now() - 700000,
  },
];
